### ISSUE TITLE
cambiare il testo del README.md

### ISSUE THREAD

**Issue by napo** [CristianCantoro/muchscraped#1]
I dati di verybello.it sono per la maggior parte pubblicati come open data dal MiBACT qui
http://www.beniculturali.it/mibac/export/MiBAC/sito-MiBAC/MenuPrincipale/Trasparenza/Open-Data/Sviluppatori/index.html
Tra l'altro accessibili via rest api in formato XML provvisto di XMLSchema.
questi dati sono distribuiti in cc-by

Per il resto poi, mancando una informazione di note legali sul sito in questione, essendo questo di una PA, l'accesso ai dati ricade sotto l'articolo 52 comma 2 del codice dell'amministrazione digitale

''2. I dati e i documenti che le amministrazioni titolari pubblicano, con qualsiasi modalità, senza l'espressa adozione di una licenza di cui all'articolo 2, comma 1, lettera h), del decreto legislativo 24 gennaio 2006, n. 36, si intendono rilasciati come dati di tipo aperto ai sensi all'articolo 68, comma 3, del presente Codice. L'eventuale adozione di una licenza di cui al citato articolo 2, comma 1, lettera h), è motivata ai sensi delle linee guida nazionali di cui al comma 7.''

che nella versione delle linee guida AgID per la valorizzazione del patrimonio informativo pubblico di giugno 2014 viene definita come licenza di default la cc-by 4.0
vedi pag 84 del documento 
http://www.agid.gov.it/sites/default/files/linee_guida/patrimoniopubblicolg2014_v0.7finale.pdf

**Comment by CristianCantoro** [comment]
Closed by https://github.com/CristianCantoro/muchscraped/commit/947665bfbe7b798a36693d7ba39998cb8e7efd41.
